package main

import (
	"flag"
	"fmt"
	"sort"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	registryImportPath = protogen.GoImportPath("core/shared/protoapi/gen/registry")
	registryPackage    = protogen.GoPackageName("registry")
)

func main() {
	var flags flag.FlagSet
	protogen.Options{ParamFunc: flags.Set}.Run(generate)
}

func generate(plugin *protogen.Plugin) error {
	plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	files := generatedFiles(plugin.Files)
	output := plugin.NewGeneratedFile("registry/registry.pb.go", registryImportPath)
	output.P("// Code generated by protoc-gen-kent-go-registry. DO NOT EDIT.")
	output.P()
	output.P("package ", registryPackage)
	output.P()
	fileDescriptorType := protogen.GoIdent{
		GoName:       "FileDescriptor",
		GoImportPath: "google.golang.org/protobuf/reflect/protoreflect",
	}
	output.P("var fileDescriptors = [...]",
		fileDescriptorType,
		"{",
	)
	for _, file := range files {
		output.P(file.GoDescriptorIdent, ",")
	}
	output.P("}")
	output.P()
	output.P("var filesByPath = map[string]", fileDescriptorType, "{")
	for _, file := range files {
		output.P(fmt.Sprintf("%q", file.Desc.Path()), ": ", file.GoDescriptorIdent, ",")
	}
	output.P("}")
	output.P()
	output.P("func File(path string) (", fileDescriptorType, ", bool) {")
	output.P("descriptor, exists := filesByPath[path]")
	output.P("return descriptor, exists")
	output.P("}")
	output.P()
	output.P("func Files(yield func(", fileDescriptorType, ") bool) {")
	output.P("for _, descriptor := range fileDescriptors {")
	output.P("if !yield(descriptor) {")
	output.P("return")
	output.P("}")
	output.P("}")
	output.P("}")
	output.P()
	output.P("func Paths(yield func(string) bool) {")
	output.P("for _, descriptor := range fileDescriptors {")
	output.P("if !yield(descriptor.Path()) {")
	output.P("return")
	output.P("}")
	output.P("}")
	output.P("}")

	return nil
}

func generatedFiles(files []*protogen.File) []*protogen.File {
	generated := make([]*protogen.File, 0, len(files))
	for _, file := range files {
		if !file.Generate {
			continue
		}
		if file.GoImportPath == "" {
			panic(fmt.Sprintf("schema %q has no Go import path", file.Desc.Path()))
		}
		generated = append(generated, file)
	}
	sort.Slice(generated, func(left, right int) bool {
		return generated[left].Desc.Path() < generated[right].Desc.Path()
	})
	return generated
}
