package main

import (
	"flag"
	"fmt"
	"sort"

	"core/tools/protobuf/internal/registrygen"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	registryImportPath     = protogen.GoImportPath("core/shared/protoapi/gen/registry")
	registryPackage        = protogen.GoPackageName("registry")
	testRegistryImportPath = protogen.GoImportPath("core/shared/protoapi/gen/testregistry")
	testRegistryPackage    = protogen.GoPackageName("testregistry")
)

func main() {
	var flags flag.FlagSet
	protogen.Options{ParamFunc: flags.Set}.Run(generate)
}

func generate(plugin *protogen.Plugin) error {
	plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	files := generatedFiles(plugin.Files)
	for _, file := range files {
		if _, err := registrygen.ClassifySchemaPath(file.Desc.Path()); err != nil {
			return err
		}
	}
	writeRegistry(
		plugin.NewGeneratedFile("registry/registry.pb.go", registryImportPath),
		registryPackage,
		filesForClass(files, registrygen.KentDomain),
	)
	writeRegistry(
		plugin.NewGeneratedFile("testregistry/registry.pb.go", testRegistryImportPath),
		testRegistryPackage,
		filesForClass(files, registrygen.Fixture),
	)
	return nil
}

func writeRegistry(
	output *protogen.GeneratedFile,
	packageName protogen.GoPackageName,
	files []*protogen.File,
) {
	output.P("// Code generated by protoc-gen-kent-go-registry. DO NOT EDIT.")
	output.P()
	output.P("package ", packageName)
	output.P()
	fileDescriptorType := protogen.GoIdent{
		GoName:       "FileDescriptor",
		GoImportPath: "google.golang.org/protobuf/reflect/protoreflect",
	}
	output.P("var fileDescriptors = [...]",
		fileDescriptorType,
		"{",
	)
	for _, file := range files {
		output.P(file.GoDescriptorIdent, ",")
	}
	output.P("}")
	output.P()
	output.P("var filesByPath = map[string]", fileDescriptorType, "{")
	for _, file := range files {
		output.P(fmt.Sprintf("%q", file.Desc.Path()), ": ", file.GoDescriptorIdent, ",")
	}
	output.P("}")
	output.P()
	output.P("var activeOperationNames = map[", protogen.GoIdent{
		GoName:       "FullName",
		GoImportPath: "google.golang.org/protobuf/reflect/protoreflect",
	}, "]string{")
	for _, file := range files {
		services := file.Services
		for _, service := range services {
			for _, method := range service.Methods {
				activeName, err := registrygen.ActiveOperationName(
					string(file.Desc.Package()),
					string(service.Desc.Name()),
					string(method.Desc.Name()),
				)
				if err != nil {
					panic(err)
				}
				output.P(fmt.Sprintf("%q", method.Desc.FullName()), ": ", fmt.Sprintf("%q", activeName), ",")
			}
		}
	}
	output.P("}")
	output.P()
	output.P("func File(path string) (", fileDescriptorType, ", bool) {")
	output.P("descriptor, exists := filesByPath[path]")
	output.P("return descriptor, exists")
	output.P("}")
	output.P()
	output.P("func ActiveOperationName(declaration ", protogen.GoIdent{
		GoName:       "FullName",
		GoImportPath: "google.golang.org/protobuf/reflect/protoreflect",
	}, ") (string, bool) {")
	output.P("name, exists := activeOperationNames[declaration]")
	output.P("return name, exists")
	output.P("}")
	output.P()
	output.P("func Files(yield func(", fileDescriptorType, ") bool) {")
	output.P("for _, descriptor := range fileDescriptors {")
	output.P("if !yield(descriptor) {")
	output.P("return")
	output.P("}")
	output.P("}")
	output.P("}")
	output.P()
	output.P("func Paths(yield func(string) bool) {")
	output.P("for _, descriptor := range fileDescriptors {")
	output.P("if !yield(descriptor.Path()) {")
	output.P("return")
	output.P("}")
	output.P("}")
	output.P("}")

}

func generatedFiles(files []*protogen.File) []*protogen.File {
	generated := make([]*protogen.File, 0, len(files))
	for _, file := range files {
		if !file.Generate {
			continue
		}
		if file.GoImportPath == "" {
			panic(fmt.Sprintf("schema %q has no Go import path", file.Desc.Path()))
		}
		generated = append(generated, file)
	}
	sort.Slice(generated, func(left, right int) bool {
		return generated[left].Desc.Path() < generated[right].Desc.Path()
	})
	return generated
}

func filesForClass(files []*protogen.File, class registrygen.SchemaClass) []*protogen.File {
	selected := make([]*protogen.File, 0, len(files))
	for _, file := range files {
		schemaClass, err := registrygen.ClassifySchemaPath(file.Desc.Path())
		if err != nil {
			panic(err)
		}
		if schemaClass == class {
			selected = append(selected, file)
		}
	}
	return selected
}
