// Code generated by metadataquerygen; DO NOT EDIT.
package sqlitegen

import (
	"context"
	"database/sql"
)

const retireDependentCurrentSessionWorkflowNodeAssociations = "\nUPDATE session_workflow_node_associations\nSET association_status = 'historical'\nWHERE task_id = ?1\n  AND association_status = 'current'\n  AND (?4 IS NULL OR transition_branch_key = ?4)\n  AND session_id IN (\n      WITH RECURSIVE dependent_sessions(session_id) AS (\n          SELECT association.session_id\n          FROM session_workflow_node_associations association\n          WHERE association.task_id = ?1\n            AND association.association_status = 'current'\n            AND association.source_session_id = ?2\n            AND association.session_id != ?3\n            AND (?4 IS NULL OR association.transition_branch_key = ?4)\n          UNION\n          SELECT association.session_id\n          FROM session_workflow_node_associations association\n          JOIN dependent_sessions dependency\n            ON association.source_session_id = dependency.session_id\n          WHERE association.task_id = ?1\n            AND association.association_status = 'current'\n            AND association.session_id != ?3\n            AND (?4 IS NULL OR association.transition_branch_key = ?4)\n      )\n      SELECT session_id\n      FROM dependent_sessions\n  );\n"

type RetireDependentCurrentSessionWorkflowNodeAssociationsParams struct {
	TaskID                   string
	ObsoleteSessionID        string
	PreservedSourceSessionID string
	TransitionBranchKey      sql.NullString
}

func (q *Queries) RetireDependentCurrentSessionWorkflowNodeAssociations(
	ctx context.Context,
	arg RetireDependentCurrentSessionWorkflowNodeAssociationsParams,
) (metadataOperationErr error) {
	if metadataOperationErr = q.beforeOperation(); metadataOperationErr != nil {
		return metadataOperationErr
	}
	defer func() {
		metadataOperationErr = q.completeOperation(ctx, "RetireDependentCurrentSessionWorkflowNodeAssociations", metadataOperationErr)
	}()
	_, err := q.db.ExecContext(
		ctx,
		retireDependentCurrentSessionWorkflowNodeAssociations,
		arg.TaskID,
		arg.ObsoleteSessionID,
		arg.PreservedSourceSessionID,
		arg.TransitionBranchKey,
	)
	return err
}
