version: "3"

method: checksum

vars:
  BUF: go run github.com/bufbuild/buf/cmd/buf@v1.72.0

tasks:
  protobuf:
    deps: [protobuf:go, protobuf:ts]

  protobuf:lint:
    cmds:
      - "{{.BUF}} lint"

  protobuf:go:
    sources:
      - api/proto/**/*.proto
      - buf.gen.go.yaml
      - buf.lock
      - buf.yaml
    generates:
      - shared/protoapi/gen/**/*.go
      - shared/protoapi/gen/kent_api.binpb
    cmds:
      - "{{.BUF}} generate --template buf.gen.go.yaml"
      - "{{.BUF}} build --as-file-descriptor-set --exclude-source-info --output shared/protoapi/gen/kent_api.binpb"

  protobuf:ts:
    sources:
      - api/proto/**/*.proto
      - buf.gen.ts.yaml
      - buf.lock
      - buf.yaml
    generates:
      - apps/desktop/packages/server-api-contract/src/gen/**/*.ts
    cmds:
      - "{{.BUF}} generate --template buf.gen.ts.yaml"
