package app

import (
	"bytes"
	"errors"
	"io"
	"strings"
	"testing"

	"core/shared/textutil"

	tea "github.com/charmbracelet/bubbletea"
	xansi "github.com/charmbracelet/x/ansi"
)

func TestExtractUITransitionIncludesInitialPrompt(t *testing.T) {
	model := &uiModel{
		uiSessionTransitionFeatureState: uiSessionTransitionFeatureState{
			exitAction:               UIActionNewSession,
			nextSessionInitialPrompt: "review prompt payload",
			nextSessionInitialInput:  textutil.Value("draft payload"),
		},
	}
	transition := extractUITransition(model)
	if transition.Action != UIActionNewSession {
		t.Fatalf("expected action %q, got %q", UIActionNewSession, transition.Action)
	}
	if transition.InitialPrompt != "review prompt payload" {
		t.Fatalf("expected initial prompt payload, got %q", transition.InitialPrompt)
	}
	if input, present := textutil.OptionalValue(transition.InitialInput); !present || input != "draft payload" {
		t.Fatalf("expected initial input payload, got %q/%t", input, present)
	}
}

type uiProgramFinalModelHarness struct {
	final *uiModel
}

type uiProgramFinalModelMsg struct{}

func (h uiProgramFinalModelHarness) Init() tea.Cmd {
	return func() tea.Msg { return uiProgramFinalModelMsg{} }
}

func (h uiProgramFinalModelHarness) Update(tea.Msg) (tea.Model, tea.Cmd) {
	return h.final, tea.Quit
}

func (uiProgramFinalModelHarness) View() string {
	return ""
}

func TestRunUIProgramSurfacesForcedExitStatusAfterLoopRestoration(t *testing.T) {
	final := newProjectedStaticUIModel()
	final.forcedLocalExit = true
	final.transientStatus = "projection failure generated by the model"
	var output bytes.Buffer
	composition := &uiProgramComposition{
		options: []tea.ProgramOption{
			tea.WithInput(nil),
			tea.WithOutput(io.Discard),
			tea.WithoutRenderer(),
		},
		output: &output,
		close:  func() {},
	}

	result, err := runUIProgram(composition, uiProgramFinalModelHarness{final: final})
	if err != nil {
		t.Fatalf("runUIProgram: %v", err)
	}
	if result != final {
		t.Fatalf("final model = %T, want projection failure UI model", result)
	}
	if got := strings.TrimSpace(output.String()); got != final.transientStatus {
		t.Fatalf("post-loop fatal status length = %d, want %d", len(got), len(final.transientStatus))
	}
}

func TestNativeProgressRequiresTerminalOutput(t *testing.T) {
	var output bytes.Buffer
	if terminalSupportsNativeProgress(&output) {
		t.Fatal("redirected output was treated as a terminal")
	}
}

func TestRunUIProgramAttemptsBestEffortNativeProgressResetWhenEnabled(t *testing.T) {
	var progress bytes.Buffer
	composition := &uiProgramComposition{
		options: []tea.ProgramOption{
			tea.WithInput(nil),
			tea.WithOutput(io.Discard),
			tea.WithoutRenderer(),
		},
		terminalOutput:        newUITerminalOutput(&progress),
		nativeProgressEnabled: true,
		close:                 func() {},
	}
	if _, err := runUIProgram(composition, uiProgramFinalModelHarness{final: newProjectedStaticUIModel()}); err != nil {
		t.Fatalf("runUIProgram: %v", err)
	}
	if got, want := progress.String(), xansi.ResetProgressBar; got != want {
		t.Fatalf("post-run native progress output = %q, want %q", got, want)
	}
}

func TestRunUIProgramCancelsPendingNativeProgressBeforeFinalReset(t *testing.T) {
	model, progress := nativeProgressTestModel(t, true)
	model.worktrees.create.submitting = true
	_ = model.reconcileNativeProgress()
	generation := model.nativeProgress.generation
	_, showCmd := model.Update(nativeProgressDelayMsg{generation: generation})
	if showCmd == nil {
		t.Fatal("eligible operation did not schedule native progress")
	}

	composition := &uiProgramComposition{
		model:                 model,
		options:               []tea.ProgramOption{tea.WithInput(nil), tea.WithOutput(io.Discard), tea.WithoutRenderer()},
		terminalOutput:        model.terminalOutput,
		nativeProgressEnabled: true,
		close:                 func() {},
	}
	if _, err := runUIProgram(composition, uiProgramFinalModelHarness{final: newProjectedStaticUIModel()}); err != nil {
		t.Fatalf("runUIProgram: %v", err)
	}
	done, ok := showCmd().(nativeProgressWriteDoneMsg)
	if !ok || !done.canceled {
		t.Fatalf("post-exit show command result = %#v, want canceled completion", showCmd())
	}
	if got, want := progress.String(), xansi.ResetProgressBar; got != want {
		t.Fatalf("post-exit native progress output = %q, want %q", got, want)
	}
}

func TestRunUIProgramSkipsNativeProgressResetWhenDisabled(t *testing.T) {
	var progress bytes.Buffer
	composition := &uiProgramComposition{
		options: []tea.ProgramOption{
			tea.WithInput(nil),
			tea.WithOutput(io.Discard),
			tea.WithoutRenderer(),
		},
		terminalOutput: newUITerminalOutput(&progress),
		close:          func() {},
	}
	if _, err := runUIProgram(composition, uiProgramFinalModelHarness{final: newProjectedStaticUIModel()}); err != nil {
		t.Fatalf("runUIProgram: %v", err)
	}
	if progress.Len() != 0 {
		t.Fatalf("disabled post-run native progress output = %q, want empty", progress.String())
	}
}

func TestRunUIProgramLogsBestEffortNativeProgressResetFailure(t *testing.T) {
	logger := &testUILogger{}
	composition := &uiProgramComposition{
		options: []tea.ProgramOption{
			tea.WithInput(nil),
			tea.WithOutput(io.Discard),
			tea.WithoutRenderer(),
		},
		logger:                logger,
		terminalOutput:        newUITerminalOutput(nativeProgressFailingWriter{}),
		nativeProgressEnabled: true,
		close:                 func() {},
	}
	if _, err := runUIProgram(composition, uiProgramFinalModelHarness{final: newProjectedStaticUIModel()}); err != nil {
		t.Fatalf("runUIProgram: %v", err)
	}
	if len(logger.lines) == 0 {
		t.Fatal("native progress reset failure was not logged")
	}
}

type nativeProgressFailingWriter struct{}

func (nativeProgressFailingWriter) Write([]byte) (int, error) {
	return 0, errors.New("native progress output failed")
}
