package app

import (
	"bytes"
	"io"
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"
)

func TestExtractUITransitionIncludesInitialPrompt(t *testing.T) {
	model := &uiModel{
		uiSessionTransitionFeatureState: uiSessionTransitionFeatureState{
			exitAction:               UIActionNewSession,
			nextSessionInitialPrompt: "review prompt payload",
			nextSessionInitialInput:  "draft payload",
		},
	}
	transition := extractUITransition(model)
	if transition.Action != UIActionNewSession {
		t.Fatalf("expected action %q, got %q", UIActionNewSession, transition.Action)
	}
	if transition.InitialPrompt != "review prompt payload" {
		t.Fatalf("expected initial prompt payload, got %q", transition.InitialPrompt)
	}
	if transition.InitialInput != "draft payload" {
		t.Fatalf("expected initial input payload, got %q", transition.InitialInput)
	}
}

type uiProgramFinalModelHarness struct {
	final *uiModel
}

type uiProgramFinalModelMsg struct{}

func (h uiProgramFinalModelHarness) Init() tea.Cmd {
	return func() tea.Msg { return uiProgramFinalModelMsg{} }
}

func (h uiProgramFinalModelHarness) Update(tea.Msg) (tea.Model, tea.Cmd) {
	return h.final, tea.Quit
}

func (uiProgramFinalModelHarness) View() string {
	return ""
}

func TestRunUIProgramSurfacesForcedExitStatusAfterLoopRestoration(t *testing.T) {
	final := newProjectedStaticUIModel()
	final.forcedLocalExit = true
	final.transientStatus = "projection failure generated by the model"
	var output bytes.Buffer
	composition := &uiProgramComposition{
		options: []tea.ProgramOption{
			tea.WithInput(nil),
			tea.WithOutput(io.Discard),
			tea.WithoutRenderer(),
		},
		output: &output,
		close:  func() {},
	}

	result, err := runUIProgram(composition, uiProgramFinalModelHarness{final: final})
	if err != nil {
		t.Fatalf("runUIProgram: %v", err)
	}
	if result != final {
		t.Fatalf("final model = %T, want projection failure UI model", result)
	}
	if got := strings.TrimSpace(output.String()); got != final.transientStatus {
		t.Fatalf("post-loop fatal status length = %d, want %d", len(got), len(final.transientStatus))
	}
}
