package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

type lifecycleQuery struct {
	name       string
	annotation string
	sql        string
}

func main() {
	input := flag.String("input", "", "lifecycle SQL input file")
	output := flag.String("output", "", "generated Go output file")
	packageName := flag.String("package", "", "generated Go package name")
	flag.Parse()

	if strings.TrimSpace(*input) == "" {
		exitWithError(errors.New("input is required"))
	}
	if strings.TrimSpace(*output) == "" {
		exitWithError(errors.New("output is required"))
	}
	if strings.TrimSpace(*packageName) == "" {
		exitWithError(errors.New("package is required"))
	}
	source, err := os.ReadFile(*input)
	if err != nil {
		exitWithError(fmt.Errorf("read input: %w", err))
	}
	generated, err := generateLifecycleGo(source, *packageName)
	if err != nil {
		exitWithError(err)
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		exitWithError(fmt.Errorf("create output dir: %w", err))
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		exitWithError(fmt.Errorf("write output: %w", err))
	}
}

func exitWithError(err error) {
	_, _ = fmt.Fprintf(os.Stderr, "sqlitelifecyclegen: %v\n", err)
	os.Exit(1)
}

func generateLifecycleGo(source []byte, packageName string) ([]byte, error) {
	queries, err := parseLifecycleQueries(string(source))
	if err != nil {
		return nil, err
	}
	expected := map[string]string{
		"DeferForeignKeys":             ":exec",
		"CreateLifecycleQuestionIndex": ":exec",
		"ClearLifecycleQuestionIndex":  ":exec",
		"InsertLifecycleQuestion":      ":exec",
		"DeleteLifecycleQuestion":      ":execrows",
		"AnchorLifecycleQuestionIndex": ":one",
		"ListLifecycleQuestions":       ":many",
	}
	if len(queries) != len(expected) {
		return nil, fmt.Errorf("expected %d lifecycle queries, got %d", len(expected), len(queries))
	}
	byName := make(map[string]lifecycleQuery, len(queries))
	for _, query := range queries {
		annotation, exists := expected[query.name]
		if !exists {
			return nil, fmt.Errorf("unsupported lifecycle query %q", query.name)
		}
		if query.annotation != annotation {
			return nil, fmt.Errorf(
				"lifecycle query %q annotation = %q, want %q",
				query.name,
				query.annotation,
				annotation,
			)
		}
		byName[query.name] = query
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by server/metadata/lifecyclegen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", packageName)
	fmt.Fprintf(&out, "import (\n")
	fmt.Fprintf(&out, "\t%q\n", "context")
	fmt.Fprintf(&out, "\t%q\n", "database/sql")
	fmt.Fprintf(&out, "\t%q\n", "fmt")
	fmt.Fprintf(&out, ")\n\n")
	fmt.Fprintf(&out, "type DBTX interface {\n")
	fmt.Fprintf(&out, "\tExecContext(context.Context, string, ...interface{}) (sql.Result, error)\n")
	fmt.Fprintf(&out, "\tQueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)\n")
	fmt.Fprintf(&out, "\tQueryRowContext(context.Context, string, ...interface{}) *sql.Row\n")
	fmt.Fprintf(&out, "}\n\n")
	fmt.Fprintf(&out, "func New(db DBTX) *Queries { return &Queries{db: db} }\n\n")
	fmt.Fprintf(&out, "type Queries struct { db DBTX }\n\n")
	fmt.Fprintf(&out, "func (q *Queries) WithTx(tx *sql.Tx) *Queries { return &Queries{db: tx} }\n\n")

	writeExecMethod(&out, byName["DeferForeignKeys"])
	writeExecMethod(&out, byName["CreateLifecycleQuestionIndex"])
	writeExecMethod(&out, byName["ClearLifecycleQuestionIndex"])

	fmt.Fprintf(&out, "type LifecycleQuestionRecord struct {\n")
	writeLifecycleQuestionFields(&out)
	fmt.Fprintf(&out, "}\n\n")

	insert := byName["InsertLifecycleQuestion"]
	writeQueryConstant(&out, insert)
	fmt.Fprintf(&out, "type InsertLifecycleQuestionParams = LifecycleQuestionRecord\n\n")
	fmt.Fprintf(&out, "func (q *Queries) InsertLifecycleQuestion(ctx context.Context, arg InsertLifecycleQuestionParams) error {\n")
	fmt.Fprintf(&out, "\t_, err := q.db.ExecContext(ctx, insertLifecycleQuestion,\n")
	writeLifecycleQuestionArguments(&out, "\t\t", "arg")
	fmt.Fprintf(&out, "\t)\n\treturn err\n}\n\n")

	deleteQuery := byName["DeleteLifecycleQuestion"]
	writeQueryConstant(&out, deleteQuery)
	fmt.Fprintf(&out, "type DeleteLifecycleQuestionParams = LifecycleQuestionRecord\n\n")
	fmt.Fprintf(&out, "func (q *Queries) DeleteLifecycleQuestion(ctx context.Context, arg DeleteLifecycleQuestionParams) (int64, error) {\n")
	fmt.Fprintf(&out, "\tresult, err := q.db.ExecContext(ctx, deleteLifecycleQuestion,\n")
	writeLifecycleQuestionArguments(&out, "\t\t", "arg")
	fmt.Fprintf(&out, "\t)\n")
	fmt.Fprintf(&out, "\tif err != nil { return 0, err }\n")
	fmt.Fprintf(&out, "\trows, err := result.RowsAffected()\n")
	fmt.Fprintf(&out, "\tif err != nil { return 0, fmt.Errorf(%q, err) }\n", "read deleted lifecycle Question count: %w")
	fmt.Fprintf(&out, "\treturn rows, nil\n}\n\n")

	anchor := byName["AnchorLifecycleQuestionIndex"]
	writeQueryConstant(&out, anchor)
	fmt.Fprintf(&out, "func (q *Queries) AnchorLifecycleQuestionIndex(ctx context.Context) (bool, error) {\n")
	fmt.Fprintf(&out, "\tvar anchored bool\n")
	fmt.Fprintf(&out, "\terr := q.db.QueryRowContext(ctx, anchorLifecycleQuestionIndex).Scan(&anchored)\n")
	fmt.Fprintf(&out, "\treturn anchored, err\n}\n\n")

	list := byName["ListLifecycleQuestions"]
	writeQueryConstant(&out, list)
	fmt.Fprintf(&out, "type ListLifecycleQuestionsParams struct {\n")
	fmt.Fprintf(&out, "\tCursorActive int64\n\tCursorOccurredAtUnixMs int64\n\tCursorItemID string\n\tLimitRows int64\n")
	fmt.Fprintf(&out, "}\n\n")
	fmt.Fprintf(&out, "type ListLifecycleQuestionsRow = LifecycleQuestionRecord\n\n")
	fmt.Fprintf(&out, "func (q *Queries) ListLifecycleQuestions(ctx context.Context, arg ListLifecycleQuestionsParams) ([]ListLifecycleQuestionsRow, error) {\n")
	fmt.Fprintf(&out, "\trows, err := q.db.QueryContext(ctx, listLifecycleQuestions,\n")
	fmt.Fprintf(&out, "\t\targ.CursorActive,\n\t\targ.CursorOccurredAtUnixMs,\n\t\targ.CursorOccurredAtUnixMs,\n\t\targ.CursorItemID,\n\t\targ.LimitRows,\n\t)\n")
	fmt.Fprintf(&out, "\tif err != nil { return nil, err }\n\tdefer rows.Close()\n")
	fmt.Fprintf(&out, "\tvar items []ListLifecycleQuestionsRow\n")
	fmt.Fprintf(&out, "\tfor rows.Next() {\n\t\tvar item ListLifecycleQuestionsRow\n")
	fmt.Fprintf(&out, "\t\tif err := rows.Scan(\n")
	writeLifecycleQuestionScanTargets(&out, "\t\t\t", "item")
	fmt.Fprintf(&out, "\t\t); err != nil { return nil, err }\n")
	fmt.Fprintf(&out, "\t\titems = append(items, item)\n\t}\n")
	fmt.Fprintf(&out, "\tif err := rows.Err(); err != nil { return nil, err }\n")
	fmt.Fprintf(&out, "\treturn items, nil\n}\n")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func writeExecMethod(out *bytes.Buffer, query lifecycleQuery) {
	writeQueryConstant(out, query)
	fmt.Fprintf(out, "func (q *Queries) %s(ctx context.Context) error {\n", query.name)
	fmt.Fprintf(out, "\t_, err := q.db.ExecContext(ctx, %s", lowerFirst(query.name))
	fmt.Fprintf(out, ")\n\treturn err\n}\n\n")
}

func writeQueryConstant(out *bytes.Buffer, query lifecycleQuery) {
	fmt.Fprintf(out, "const %s = %q\n\n", lowerFirst(query.name), query.sql)
}

func writeLifecycleQuestionFields(out *bytes.Buffer) {
	fmt.Fprintf(out, "\tOccurredAtUnixMs int64\n")
	fmt.Fprintf(out, "\tItemID string\n")
	fmt.Fprintf(out, "\tTaskID string\n")
	fmt.Fprintf(out, "\tNodeID string\n")
	fmt.Fprintf(out, "\tTransitionBranchKey sql.NullString\n")
	fmt.Fprintf(out, "\tScopeID string\n")
	fmt.Fprintf(out, "\tPromptID string\n")
}

func writeLifecycleQuestionArguments(out *bytes.Buffer, indent string, variable string) {
	for _, field := range []string{
		"OccurredAtUnixMs",
		"ItemID",
		"TaskID",
		"NodeID",
		"TransitionBranchKey",
		"ScopeID",
		"PromptID",
	} {
		fmt.Fprintf(out, "%s%s.%s,\n", indent, variable, field)
	}
}

func writeLifecycleQuestionScanTargets(out *bytes.Buffer, indent string, variable string) {
	for _, field := range []string{
		"OccurredAtUnixMs",
		"ItemID",
		"TaskID",
		"NodeID",
		"TransitionBranchKey",
		"ScopeID",
		"PromptID",
	} {
		fmt.Fprintf(out, "%s&%s.%s,\n", indent, variable, field)
	}
}

func lowerFirst(name string) string {
	runes := []rune(name)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func parseLifecycleQueries(source string) ([]lifecycleQuery, error) {
	lines := strings.Split(source, "\n")
	queries := make([]lifecycleQuery, 0)
	var activeName string
	var activeAnnotation string
	activeSQL := make([]string, 0)
	flush := func() error {
		if activeName == "" {
			return nil
		}
		sql := strings.TrimSpace(strings.Join(activeSQL, "\n"))
		if sql == "" {
			return fmt.Errorf("lifecycle query %q has empty body", activeName)
		}
		queries = append(queries, lifecycleQuery{
			name:       activeName,
			annotation: activeAnnotation,
			sql:        sql,
		})
		activeName = ""
		activeAnnotation = ""
		activeSQL = activeSQL[:0]
		return nil
	}
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "-- name:") {
			if err := flush(); err != nil {
				return nil, err
			}
			name, annotation, err := parseLifecycleName(trimmed)
			if err != nil {
				return nil, err
			}
			activeName = name
			activeAnnotation = annotation
			continue
		}
		if activeName != "" {
			activeSQL = append(activeSQL, line)
		}
	}
	if err := flush(); err != nil {
		return nil, err
	}
	return queries, nil
}

func parseLifecycleName(line string) (string, string, error) {
	fields := strings.Fields(strings.TrimPrefix(line, "-- name:"))
	if len(fields) != 2 {
		return "", "", fmt.Errorf("invalid lifecycle query declaration %q", line)
	}
	if !isExportedIdentifier(fields[0]) {
		return "", "", fmt.Errorf("invalid lifecycle query name %q", fields[0])
	}
	switch fields[1] {
	case ":exec", ":execrows", ":one", ":many":
	default:
		return "", "", fmt.Errorf("invalid lifecycle query annotation %q", fields[1])
	}
	return fields[0], fields[1], nil
}

func isExportedIdentifier(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		switch {
		case i == 0:
			if !unicode.IsUpper(r) {
				return false
			}
		case !(r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r)):
			return false
		}
	}
	return true
}
