package main

import (
	"flag"
	"path"
	"sort"
	"strings"

	"core/tools/protobuf/internal/registrygen"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	registryPath     = "registry/registry.ts"
	testRegistryPath = "test-registry/registry.ts"
)

func main() {
	var flags flag.FlagSet
	protogen.Options{ParamFunc: flags.Set}.Run(generate)
}

func generate(plugin *protogen.Plugin) error {
	plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	files := generatedFiles(plugin.Files)
	for _, file := range files {
		if _, err := registrygen.ClassifySchemaPath(file.Desc.Path()); err != nil {
			return err
		}
	}
	writeRegistry(
		plugin.NewGeneratedFile(registryPath, ""),
		filesForClass(files, registrygen.KentDomain),
	)
	writeRegistry(
		plugin.NewGeneratedFile(testRegistryPath, ""),
		filesForClass(files, registrygen.Fixture),
	)
	return nil
}

func writeRegistry(output *protogen.GeneratedFile, files []*protogen.File) {
	output.P("// @generated by protoc-gen-kent-ts-registry. DO NOT EDIT.")
	output.P()
	output.P(`import type { GenFile } from "@bufbuild/protobuf/codegenv2";`)
	for _, file := range files {
		output.P(
			`import { `,
			descriptorIdentifier(file.Desc.Path()),
			` } from "`,
			modulePath(file.Desc.Path()),
			`";`,
		)
	}
	output.P()
	for _, file := range files {
		output.P(`export * as `, exportIdentifier(file.Desc.Path()), ` from "`, modulePath(file.Desc.Path()), `";`)
	}
	output.P()
	output.P("export const fileDescriptors: readonly GenFile[] = [")
	for _, file := range files {
		output.P("  ", descriptorIdentifier(file.Desc.Path()), ",")
	}
	output.P("];")
	output.P()
	output.P("export const descriptorPaths: readonly string[] = fileDescriptors.map(")
	output.P("  (descriptor) => `${descriptor.name}.proto`,")
	output.P(");")
}

func generatedFiles(files []*protogen.File) []*protogen.File {
	generated := make([]*protogen.File, 0, len(files))
	for _, file := range files {
		if file.Generate {
			generated = append(generated, file)
		}
	}
	sort.Slice(generated, func(left, right int) bool {
		return generated[left].Desc.Path() < generated[right].Desc.Path()
	})
	return generated
}

func filesForClass(files []*protogen.File, class registrygen.SchemaClass) []*protogen.File {
	selected := make([]*protogen.File, 0, len(files))
	for _, file := range files {
		schemaClass, err := registrygen.ClassifySchemaPath(file.Desc.Path())
		if err != nil {
			panic(err)
		}
		if schemaClass == class {
			selected = append(selected, file)
		}
	}
	return selected
}

func modulePath(schemaPath string) string {
	base := strings.TrimSuffix(schemaPath, path.Ext(schemaPath)) + "_pb.js"
	return "../" + base
}

func descriptorIdentifier(schemaPath string) string {
	return generatedIdentifier("file_", schemaPath)
}

func exportIdentifier(schemaPath string) string {
	return generatedIdentifier("schema_", schemaPath)
}

func generatedIdentifier(prefix string, schemaPath string) string {
	var identifier strings.Builder
	identifier.WriteString(prefix)
	for _, character := range strings.TrimSuffix(schemaPath, path.Ext(schemaPath)) {
		switch {
		case character >= 'a' && character <= 'z':
			identifier.WriteRune(character)
		case character >= 'A' && character <= 'Z':
			identifier.WriteRune(character)
		case character >= '0' && character <= '9':
			identifier.WriteRune(character)
		default:
			identifier.WriteByte('_')
		}
	}
	return identifier.String()
}
