package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type taskLabelFilterTemplateData struct {
	FilterKind string
	FilterMode string
	Indent     string
	LabelIDs   string
	TaskID     string
}

func main() {
	if err := runCommand(os.Args[1:]); err != nil {
		exitWithError(err)
	}
}

func runCommand(args []string) error {
	if len(args) == 0 {
		return errors.New("command is required: render or annotate-sqlc")
	}
	switch args[0] {
	case "render":
		return renderQueriesCommand(args[1:])
	case "annotate-sqlc":
		return annotateSQLCCommand(args[1:])
	default:
		return fmt.Errorf("unknown command %q: expected render or annotate-sqlc", args[0])
	}
}

func renderQueriesCommand(args []string) error {
	fs := flag.NewFlagSet("render", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	input := fs.String("input", "", "metadata query template input file")
	fragment := fs.String("fragment", "", "task label filter template fragment")
	output := fs.String("output", "", "generated metadata query output file")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return fmt.Errorf("render does not accept positional arguments")
	}
	if strings.TrimSpace(*input) == "" {
		return errors.New("input is required")
	}
	if strings.TrimSpace(*fragment) == "" {
		return errors.New("fragment is required")
	}
	if strings.TrimSpace(*output) == "" {
		return errors.New("output is required")
	}
	source, err := os.ReadFile(*input)
	if err != nil {
		return fmt.Errorf("read input: %w", err)
	}
	filterSource, err := os.ReadFile(*fragment)
	if err != nil {
		return fmt.Errorf("read fragment: %w", err)
	}
	generated, err := generateQueries(source, filterSource)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	return nil
}

func annotateSQLCCommand(args []string) error {
	fs := flag.NewFlagSet("annotate-sqlc", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	input := fs.String("input", "", "sqlc-generated Go source to annotate")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return fmt.Errorf("annotate-sqlc does not accept positional arguments")
	}
	if strings.TrimSpace(*input) == "" {
		return errors.New("input is required")
	}
	return annotateFile(*input)
}

func exitWithError(err error) {
	_, _ = fmt.Fprintf(os.Stderr, "metadataquerygen: %v\n", err)
	os.Exit(1)
}

func generateQueries(source []byte, filterSource []byte) ([]byte, error) {
	filterTemplate, err := template.New("task_label_filter").Option("missingkey=error").Parse(string(filterSource))
	if err != nil {
		return nil, fmt.Errorf("parse task label filter template: %w", err)
	}
	renderTaskLabelFilter := func(
		indent string,
		taskID string,
		filterKind string,
		filterMode string,
		labelIDs string,
	) (string, error) {
		data := taskLabelFilterTemplateData{
			FilterKind: filterKind,
			FilterMode: filterMode,
			Indent:     indent,
			LabelIDs:   labelIDs,
			TaskID:     taskID,
		}
		if err := data.validate(); err != nil {
			return "", err
		}
		var rendered bytes.Buffer
		if err := filterTemplate.Execute(&rendered, data); err != nil {
			return "", fmt.Errorf("render task label filter template: %w", err)
		}
		return rendered.String(), nil
	}
	queryTemplate, err := template.New("queries").
		Option("missingkey=error").
		Funcs(template.FuncMap{"taskLabelFilter": renderTaskLabelFilter}).
		Parse(string(source))
	if err != nil {
		return nil, fmt.Errorf("parse metadata query template: %w", err)
	}
	var generated bytes.Buffer
	if err := queryTemplate.Execute(&generated, nil); err != nil {
		return nil, fmt.Errorf("render metadata query template: %w", err)
	}
	return generated.Bytes(), nil
}

func (d taskLabelFilterTemplateData) validate() error {
	switch {
	case strings.TrimSpace(d.TaskID) == "":
		return errors.New("task ID template expression is empty")
	case strings.TrimSpace(d.FilterKind) == "":
		return errors.New("filter kind template expression is empty")
	case strings.TrimSpace(d.FilterMode) == "":
		return errors.New("filter mode template expression is empty")
	case strings.TrimSpace(d.LabelIDs) == "":
		return errors.New("label IDs template expression is empty")
	default:
		return nil
	}
}
