package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
)

func generateQueriesDB(path string) error {
	source, err := format.Source([]byte(`// Code generated by metadataquerygen; DO NOT EDIT.

package sqlitegen

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func NewRaw(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx DBTX) *Queries {
	return &Queries{db: tx}
}
`))
	if err != nil {
		return fmt.Errorf("format generated SQLite DB adapter: %w", err)
	}
	current, err := os.ReadFile(path)
	if err == nil && bytes.Equal(current, source) {
		return nil
	}
	if err := os.WriteFile(path, source, 0o644); err != nil {
		return fmt.Errorf("write generated SQLite DB adapter: %w", err)
	}
	return nil
}
