package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"strconv"
)

func generateTaskSearchPageDescriptors(query []byte) ([]byte, error) {
	if len(bytes.TrimSpace(query)) == 0 {
		return nil, errors.New("task-search page descriptor query is empty")
	}
	source := `// Code generated by metadataquerygen; DO NOT EDIT.

package sqlitegen

import (
	"context"
	"database/sql"

	"core/shared/runtimeids"
)

const listTaskSearchPageDescriptors = ` + strconv.Quote(string(query)) + `

type ListTaskSearchPageDescriptorsParams struct {
	Mode                      string
	CandidateExpression       string
	LiteralQuery              string
	CaseMode                  int64
	IncludeComments           int64
	ProjectIdsJson            sql.NullString
	StatusKindsJson           sql.NullString
	ContextClusters           int64
	OffsetRows                int64
	LimitRows                 int64
	LiveTaskStatesJson        string
	ShortIDCaseMode           int64
}

type ListTaskSearchPageDescriptorsRow struct {
	TaskID             string
	ProjectID          string
	ProjectKey         string
	ShortID            string
	WorkflowID         runtimeids.WorkflowID
	TaskTitle          string
	IsDone             int64
	StatusKind         interface{}
	NodeIdsJson        interface{}
	AttentionTypesJson interface{}
	DocumentID         int64
	SourceKind         string
	CommentID          sql.NullString
	TotalHitCount      int64
	Ordinal            int64
	SourceOrdinal      int64
	TaskWeightedRank   float64
	RawSnippet         interface{}
}

func (q *Queries) ListTaskSearchPageDescriptors(ctx context.Context, arg ListTaskSearchPageDescriptorsParams) ([]ListTaskSearchPageDescriptorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskSearchPageDescriptors,
		arg.Mode,
		arg.CandidateExpression,
		arg.LiteralQuery,
		arg.CaseMode,
		arg.IncludeComments,
		arg.ProjectIdsJson,
		arg.StatusKindsJson,
		arg.ContextClusters,
		arg.OffsetRows,
		arg.LimitRows,
		arg.LiveTaskStatesJson,
		arg.ShortIDCaseMode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskSearchPageDescriptorsRow
	for rows.Next() {
		var item ListTaskSearchPageDescriptorsRow
		if err := rows.Scan(
			&item.TaskID,
			&item.ProjectID,
			&item.ProjectKey,
			&item.ShortID,
			&item.WorkflowID,
			&item.TaskTitle,
			&item.IsDone,
			&item.StatusKind,
			&item.NodeIdsJson,
			&item.AttentionTypesJson,
			&item.DocumentID,
			&item.SourceKind,
			&item.CommentID,
			&item.TotalHitCount,
			&item.Ordinal,
			&item.SourceOrdinal,
			&item.TaskWeightedRank,
			&item.RawSnippet,
		); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
`
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated task-search page descriptor adapter: %w", err)
	}
	return annotateSource(formatted)
}

func generateTaskSearchSchemaContract(query []byte) ([]byte, error) {
	if len(bytes.TrimSpace(query)) == 0 {
		return nil, errors.New("task-search schema contract query is empty")
	}
	source := `// Code generated by metadataquerygen; DO NOT EDIT.

package sqlitegen

import "context"

const listTaskSearchSchemaContractFailures = ` + strconv.Quote(string(query)) + `

func (q *Queries) ListTaskSearchSchemaContractFailures(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTaskSearchSchemaContractFailures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var failures []string
	for rows.Next() {
		var failure string
		if err := rows.Scan(&failure); err != nil {
			return nil, err
		}
		failures = append(failures, failure)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return failures, nil
}
`
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated task-search schema contract adapter: %w", err)
	}
	return annotateSource(formatted)
}
