package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func generateTaskSearchPageDescriptorsCommand(args []string) error {
	fs := flag.NewFlagSet("generate-task-search-page-descriptors", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	input := fs.String("input", "", "metadata query template input")
	fragment := fs.String("fragment", "", "task label filter template fragment")
	statusFragment := fs.String("status-fragment", "", "task status projection template fragment")
	output := fs.String("output", "", "generated Go output")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return errors.New("generate-task-search-page-descriptors does not accept positional arguments")
	}
	for name, value := range map[string]string{
		"input":           *input,
		"fragment":        *fragment,
		"status-fragment": *statusFragment,
		"output":          *output,
	} {
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("%s is required", name)
		}
	}
	querySource, err := os.ReadFile(*input)
	if err != nil {
		return fmt.Errorf("read query template: %w", err)
	}
	filterSource, err := os.ReadFile(*fragment)
	if err != nil {
		return fmt.Errorf("read task label filter template: %w", err)
	}
	statusSource, err := os.ReadFile(*statusFragment)
	if err != nil {
		return fmt.Errorf("read task status projection template: %w", err)
	}
	query, err := renderTaskSearchPageDescriptors(querySource, filterSource, statusSource)
	if err != nil {
		return err
	}
	generated, err := generateTaskSearchPageDescriptors(query)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		return fmt.Errorf("create generated query directory: %w", err)
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		return fmt.Errorf("write generated page descriptor adapter: %w", err)
	}
	return nil
}

func generateTaskSearchPageDescriptors(query []byte) ([]byte, error) {
	if len(bytes.TrimSpace(query)) == 0 {
		return nil, errors.New("task-search page descriptor query is empty")
	}
	source := `// Code generated by metadataquerygen; DO NOT EDIT.

package sqlitegen

import (
	"context"
	"database/sql"
)

const listTaskSearchPageDescriptors = ` + strconv.Quote(string(query)) + `

type ListTaskSearchPageDescriptorsParams struct {
	Mode                      string
	CandidateExpression       string
	LiteralQuery              string
	CaseMode                  int64
	IncludeComments           int64
	ProjectIdsJson            string
	StatusFilterSet           int64
	StatusKindsJson           string
	ContextClusters           int64
	CursorSet                 int64
	CursorOrdinal             int64
	CursorWeightedRank        sql.NullFloat64
	CursorTaskID              string
	LimitRows                 int64
	AuthorityObservationsJson string
	CurrentRunFactsJson       string
}

type ListTaskSearchPageDescriptorsRow struct {
	TaskID             string
	ProjectID          string
	ProjectKey         string
	ShortID            string
	WorkflowID         string
	TaskTitle          string
	IsDone             int64
	StatusKind         interface{}
	NodeIdsJson        interface{}
	RunIdsJson         interface{}
	AttentionTypesJson interface{}
	DocumentID         int64
	SourceKind         string
	CommentID          sql.NullString
	TotalHitCount      int64
	Ordinal            int64
	SourceOrdinal      int64
	TaskWeightedRank   float64
	RawSnippet         interface{}
}

func (q *Queries) ListTaskSearchPageDescriptors(ctx context.Context, arg ListTaskSearchPageDescriptorsParams) ([]ListTaskSearchPageDescriptorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskSearchPageDescriptors,
		arg.Mode,
		arg.CandidateExpression,
		arg.LiteralQuery,
		arg.CaseMode,
		arg.IncludeComments,
		arg.ProjectIdsJson,
		arg.StatusFilterSet,
		arg.StatusKindsJson,
		arg.ContextClusters,
		arg.CursorSet,
		arg.CursorOrdinal,
		arg.CursorWeightedRank,
		arg.CursorTaskID,
		arg.LimitRows,
		arg.AuthorityObservationsJson,
		arg.CurrentRunFactsJson,
	)
	err = recordQueryError(ctx, err, listTaskSearchPageDescriptors, 16)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskSearchPageDescriptorsRow
	for rows.Next() {
		var item ListTaskSearchPageDescriptorsRow
		if err := recordQueryError(ctx, rows.Scan(
			&item.TaskID,
			&item.ProjectID,
			&item.ProjectKey,
			&item.ShortID,
			&item.WorkflowID,
			&item.TaskTitle,
			&item.IsDone,
			&item.StatusKind,
			&item.NodeIdsJson,
			&item.RunIdsJson,
			&item.AttentionTypesJson,
			&item.DocumentID,
			&item.SourceKind,
			&item.CommentID,
			&item.TotalHitCount,
			&item.Ordinal,
			&item.SourceOrdinal,
			&item.TaskWeightedRank,
			&item.RawSnippet,
		), listTaskSearchPageDescriptors, 16); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := recordQueryError(ctx, rows.Close(), listTaskSearchPageDescriptors, 16); err != nil {
		return nil, err
	}
	if err := recordQueryError(ctx, rows.Err(), listTaskSearchPageDescriptors, 16); err != nil {
		return nil, err
	}
	return items, nil
}
`
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated task-search page descriptor adapter: %w", err)
	}
	return formatted, nil
}
