package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"strconv"
)

func generateWorkflowSessionDependencyInvalidation(query []byte) ([]byte, error) {
	if len(bytes.TrimSpace(query)) == 0 {
		return nil, errors.New("Workflow Session dependency invalidation query is empty")
	}
	source := `// Code generated by metadataquerygen; DO NOT EDIT.

package sqlitegen

import "context"

const retireDependentCurrentSessionWorkflowNodeAssociations = ` + strconv.Quote(string(query)) + `

type RetireDependentCurrentSessionWorkflowNodeAssociationsParams struct {
	TaskID                   string
	ObsoleteSessionID        string
	PreservedSourceSessionID string
}

func (q *Queries) RetireDependentCurrentSessionWorkflowNodeAssociations(
	ctx context.Context,
	arg RetireDependentCurrentSessionWorkflowNodeAssociationsParams,
) error {
	_, err := q.db.ExecContext(
		ctx,
		retireDependentCurrentSessionWorkflowNodeAssociations,
		arg.TaskID,
		arg.ObsoleteSessionID,
		arg.PreservedSourceSessionID,
	)
	return recordQueryError(ctx, err, retireDependentCurrentSessionWorkflowNodeAssociations, 3)
}
`
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated Workflow Session dependency invalidation adapter: %w", err)
	}
	return formatted, nil
}
