#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

render_install() {
	printf '%s\n' \
		'#!/usr/bin/env sh' \
		'set -eu' \
		'' \
		'# Code generated by scripts/generate-install.sh; DO NOT EDIT.'
	cat "$repo_root/scripts/lib/checksum.sh"
	printf '\n'
	cat "$repo_root/scripts/install.sh.body"
}

if [[ "${1:-}" == "--check" ]]; then
	if ! cmp -s <(render_install) "$repo_root/scripts/install.sh"; then
		echo "scripts/install.sh is stale; run bash scripts/generate-install.sh" >&2
		exit 1
	fi
	exit 0
fi

output_path="${1:-$repo_root/scripts/install.sh}"
render_install >"$output_path"
