// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitelifecyclegen

import (
	"database/sql"
)

type LifecycleQuestionIndex struct {
	OccurredAtUnixMs       int64
	ItemID                 string
	TaskID                 string
	NodeID                 string
	TransitionBranchKey    sql.NullString
	ScopeID                string
	PromptID               string
	PromptKind             int64
	Question               string
	SuggestionsJson        string
	RecommendedOptionIndex sql.NullInt64
	ApprovalDecisionsJson  string
}
