// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lifecycle_question_index.sql

package sqlitelifecyclegen

import (
	"context"
	"database/sql"
)

const anchorLifecycleQuestionIndex = `-- name: AnchorLifecycleQuestionIndex :one
SELECT EXISTS(
    SELECT 1
    FROM lifecycle_question_index
) AS anchored
`

func (q *Queries) AnchorLifecycleQuestionIndex(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, anchorLifecycleQuestionIndex)
	var anchored bool
	err := row.Scan(&anchored)
	return anchored, err
}

const clearLifecycleQuestionIndex = `-- name: ClearLifecycleQuestionIndex :exec
DELETE FROM lifecycle_question_index
`

func (q *Queries) ClearLifecycleQuestionIndex(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearLifecycleQuestionIndex)
	return err
}

const createLifecycleQuestionIndex = `-- name: CreateLifecycleQuestionIndex :exec
CREATE TABLE IF NOT EXISTS lifecycle_question_index (
    occurred_at_unix_ms INTEGER NOT NULL CHECK (occurred_at_unix_ms > 0),
    item_id TEXT NOT NULL CHECK (item_id <> '' AND item_id = trim(item_id)),
    task_id TEXT NOT NULL CHECK (task_id <> '' AND task_id = trim(task_id)),
    node_id TEXT NOT NULL CHECK (node_id <> '' AND node_id = trim(node_id)),
    transition_branch_key TEXT CHECK (
        transition_branch_key IS NULL
        OR (transition_branch_key <> '' AND transition_branch_key = trim(transition_branch_key))
    ),
    scope_id TEXT NOT NULL CHECK (scope_id <> '' AND scope_id = trim(scope_id)),
    prompt_id TEXT NOT NULL CHECK (prompt_id <> '' AND prompt_id = trim(prompt_id)),
    prompt_kind INTEGER NOT NULL CHECK (prompt_kind IN (1, 2)),
    question TEXT NOT NULL,
    suggestions_json TEXT NOT NULL CHECK (json_valid(suggestions_json) AND json_type(suggestions_json) = 'array'),
    recommended_option_index INTEGER,
    approval_decisions_json TEXT NOT NULL CHECK (
        json_valid(approval_decisions_json)
        AND json_type(approval_decisions_json) = 'array'
    ),
    PRIMARY KEY (occurred_at_unix_ms DESC, item_id DESC)
)
`

func (q *Queries) CreateLifecycleQuestionIndex(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createLifecycleQuestionIndex)
	return err
}

const deleteLifecycleQuestion = `-- name: DeleteLifecycleQuestion :execrows
DELETE FROM lifecycle_question_index
WHERE occurred_at_unix_ms = ?1
  AND item_id = ?2
  AND task_id = ?3
  AND node_id = ?4
  AND transition_branch_key IS ?5
  AND scope_id = ?6
  AND prompt_id = ?7
`

type DeleteLifecycleQuestionParams struct {
	OccurredAtUnixMs    int64
	ItemID              string
	TaskID              string
	NodeID              string
	TransitionBranchKey sql.NullString
	ScopeID             string
	PromptID            string
}

func (q *Queries) DeleteLifecycleQuestion(ctx context.Context, arg DeleteLifecycleQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLifecycleQuestion,
		arg.OccurredAtUnixMs,
		arg.ItemID,
		arg.TaskID,
		arg.NodeID,
		arg.TransitionBranchKey,
		arg.ScopeID,
		arg.PromptID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertLifecycleQuestion = `-- name: InsertLifecycleQuestion :exec
INSERT INTO lifecycle_question_index (
    occurred_at_unix_ms,
    item_id,
    task_id,
    node_id,
    transition_branch_key,
    scope_id,
    prompt_id,
    prompt_kind,
    question,
    suggestions_json,
    recommended_option_index,
    approval_decisions_json
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
)
`

type InsertLifecycleQuestionParams struct {
	OccurredAtUnixMs       int64
	ItemID                 string
	TaskID                 string
	NodeID                 string
	TransitionBranchKey    sql.NullString
	ScopeID                string
	PromptID               string
	PromptKind             int64
	Question               string
	SuggestionsJSON        string
	RecommendedOptionIndex sql.NullInt64
	ApprovalDecisionsJSON  string
}

func (q *Queries) InsertLifecycleQuestion(ctx context.Context, arg InsertLifecycleQuestionParams) error {
	_, err := q.db.ExecContext(ctx, insertLifecycleQuestion,
		arg.OccurredAtUnixMs,
		arg.ItemID,
		arg.TaskID,
		arg.NodeID,
		arg.TransitionBranchKey,
		arg.ScopeID,
		arg.PromptID,
		arg.PromptKind,
		arg.Question,
		arg.SuggestionsJSON,
		arg.RecommendedOptionIndex,
		arg.ApprovalDecisionsJSON,
	)
	return err
}

const listLifecycleQuestions = `-- name: ListLifecycleQuestions :many
SELECT
    occurred_at_unix_ms,
    item_id,
    task_id,
    node_id,
    transition_branch_key,
    scope_id,
    prompt_id,
    prompt_kind,
    question,
    suggestions_json,
    recommended_option_index,
    approval_decisions_json
FROM lifecycle_question_index
WHERE CAST(?1 AS INTEGER) = 0
   OR occurred_at_unix_ms < ?2
   OR (
       occurred_at_unix_ms = ?2
       AND item_id < ?3
   )
ORDER BY occurred_at_unix_ms DESC, item_id DESC
LIMIT ?4
`

type ListLifecycleQuestionsParams struct {
	CursorActive           int64
	CursorOccurredAtUnixMs int64
	CursorItemID           string
	LimitRows              int64
}

func (q *Queries) ListLifecycleQuestions(ctx context.Context, arg ListLifecycleQuestionsParams) ([]LifecycleQuestionRecord, error) {
	rows, err := q.db.QueryContext(ctx, listLifecycleQuestions,
		arg.CursorActive,
		arg.CursorOccurredAtUnixMs,
		arg.CursorItemID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LifecycleQuestionRecord
	for rows.Next() {
		var i LifecycleQuestionRecord
		if err := rows.Scan(
			&i.OccurredAtUnixMs,
			&i.ItemID,
			&i.TaskID,
			&i.NodeID,
			&i.TransitionBranchKey,
			&i.ScopeID,
			&i.PromptID,
			&i.PromptKind,
			&i.Question,
			&i.SuggestionsJSON,
			&i.RecommendedOptionIndex,
			&i.ApprovalDecisionsJSON,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifecycleQuestionsForTask = `-- name: ListLifecycleQuestionsForTask :many
SELECT
    occurred_at_unix_ms,
    item_id,
    task_id,
    node_id,
    transition_branch_key,
    scope_id,
    prompt_id,
    prompt_kind,
    question,
    suggestions_json,
    recommended_option_index,
    approval_decisions_json
FROM lifecycle_question_index
WHERE task_id = ?1
ORDER BY occurred_at_unix_ms DESC, item_id DESC
`

func (q *Queries) ListLifecycleQuestionsForTask(ctx context.Context, taskID string) ([]LifecycleQuestionRecord, error) {
	rows, err := q.db.QueryContext(ctx, listLifecycleQuestionsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LifecycleQuestionRecord
	for rows.Next() {
		var i LifecycleQuestionRecord
		if err := rows.Scan(
			&i.OccurredAtUnixMs,
			&i.ItemID,
			&i.TaskID,
			&i.NodeID,
			&i.TransitionBranchKey,
			&i.ScopeID,
			&i.PromptID,
			&i.PromptKind,
			&i.Question,
			&i.SuggestionsJSON,
			&i.RecommendedOptionIndex,
			&i.ApprovalDecisionsJSON,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
