// Code generated by server/metadata/lifecyclegen. DO NOT EDIT.

package sqlitelifecyclegen

import (
	"context"
)

const deferForeignKeys = "PRAGMA defer_foreign_keys = ON;"

func (q *Queries) DeferForeignKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deferForeignKeys)
	return err
}
